VERSION 1.1.1 AFTER FIXED BUGS V 1.1.0 AFTER QA OK

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -61,5 +61,22 @@ jobs:
               docker rmi "$IMAGE_NAME" &&
               echo "$IMAGE_NAME"
             fi;
-            docker compose up servicio-gateway-server -d'
+            docker compose up servicio-gateway-server -d &&
+            # Inicializar el contador
+            counter=0
+            max_retries=5
+
+            # Esperar a que la imagen "galileo/servicio-gateway-server:1.1.1" esté lista
+            while ! docker images | grep -E "^galileo\/servicio-gateway-server\s+1.1.1"; do
+              echo "Esperando a que la imagen servicio-gateway-server:1.1.1 esté lista..."
+              sleep 5
+              counter=$((counter+1))
+
+              # Verificar si el número de intentos ha alcanzado el límite
+              if [ $counter -ge $max_retries ]; then
+                echo "Se alcanzó el número máximo de intentos. Abortando."
+                exit 1
+              fi
+            done
+            docker save -o /home/mome/galileo-images-v1.1/servicio-gateway-server_1.1.1.tar.gz galileo/servicio-gateway-server:1.1.1'
             exit
